version: '3.3'

services:
  udsctf:
    build: .
    image: udsctf:latest
    container_name: udsctf-container
    privileged: true  # 需要privileged权限来创建CAN接口
    ports:
      - "2222:22"  # SSH端口
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 可选：挂载日志目录
      - ./logs:/var/log
    networks:
      - udsctf-network

networks:
  udsctf-network:
    driver: bridge 